In [6]:
import numpy as np
%timeit np.arange(1,8)**4

3.51 µs ± 19.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [2]:
%timeit [j**4 for j in range(1,9)]

2.47 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
x=[1,2,5,6,7]
y = np.array(x)
print(y)
y
print(y.ndim)

[1 2 5 6 7]
1


In [21]:
list1 = []
for i in range(1,5):
    var = int(input("Enter the value :"))
    list1.append(var)
con=np.array(list1) 
print(con)
print(type(con))
print(list1)            

Enter the value : 11
Enter the value : 22
Enter the value : 33
Enter the value : 44


[11 22 33 44]
<class 'numpy.ndarray'>
[11, 22, 33, 44]


In [25]:
array2 = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(array2)
print(array2.ndim)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]
3


In [31]:
arex3 = np.array([[[1,2,3,4],[5,6,7,8],[9,8,76,5]]])
print(arex3)
print(type(arex3))
print(arex3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9  8 76  5]]]
<class 'numpy.ndarray'>
3


In [36]:
arex4 = np.array([1,2,3,4], ndmin = 10)
print(arex4)
print(arex4.ndim)


[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
