In [1]:
#Matrix Operations

import numpy as np

var1=([[1,2,3,4],[6,7,8,9]])
print(var1)

vp=np.matrix(var1)
print(vp)#Matrix Operations

import numpy as np

var1=([[1,2,3,4],[6,7,8,9]])
print(var1)

vp=np.matrix(var1)
print(vp)

[[1, 2, 3, 4], [6, 7, 8, 9]]
[[1 2 3 4]
 [6 7 8 9]]
[[1, 2, 3, 4], [6, 7, 8, 9]]
[[1 2 3 4]
 [6 7 8 9]]


In [2]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(var1.dtype)
type(var1)

[[1 2 3]
 [1 2 3]]
int32


numpy.ndarray

In [6]:
import numpy as np

var=np.matrix([[1,2],[5,6]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print()
print(var2)
print()
print(var*var2)
print()
print(var.dot(var2))

[[1 2]
 [5 6]]

[[1 2]
 [1 2]]

[[ 3  6]
 [11 22]]

[[ 3  6]
 [11 22]]


In [8]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1*var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[1 4 9]
 [1 4 9]]
