In [1]:
#Arithmetic Operations

In [1]:
#Addition of two arrays 
#First way
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [3]:
#Second way
var1 = np.array([7,6,4,5,3])
var2 = np.array([9,3,5,4,6])
var3 = var1 + var2
print(var3)

[16  9  9  9  9]


In [4]:
#Subtraction of two numbers
#First way
var4 = np.array([3,4,5,6])
var5 = var4 - 2
print(var5)

[1 2 3 4]


In [5]:
#Second way
array1= np.array([34,56,78,90,23,45])
array2 = np.array([4,5,6,7,8,9])
array3 = array1-array2
print(array3)

[30 51 72 83 15 36]


In [6]:
#Multiplication of two numbers
#First way
arrayex1 = np.array([45,67,89,33])
arrayex3 = arrayex1 * 2
print(arrayex3)

[ 90 134 178  66]


In [7]:
#second way
arrayex1 = np.array([45,67,89,33])
arrayex2 = np.array([33,76,89,22])
arrayex3 = arrayex1 * arrayex2
print(arrayex3)

[1485 5092 7921  726]


In [8]:
#Division of two numbers
#First way
arrayex1 = np.array([44,66,88,34])
arrayex3 = arrayex1 / 2
print(arrayex3)

[22. 33. 44. 17.]


In [9]:
#second way
arrayex1 = np.array([44,66,88,34])
arrayex2 = np.array([2,2,2,2])
arrayex3 = arrayex1 / arrayex2
print(arrayex3)

[22. 33. 44. 17.]


In [13]:
#Modulous operation of two arrays
#First way
arrayex1 = np.array([41,66,85,34])
arrayex3 = arrayex1 % 3
print(arrayex3)


[2 0 1 1]


In [15]:
#second way
arrayex1 = np.array([44,66,88,34])
arrayex2 = np.array([3,3,3,3])
arrayex3 = arrayex1 % arrayex2
print(arrayex3)

[2 0 1 1]


In [2]:
#2D Arrays

In [7]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[11,12,13,14],[11,12,13,14]])
print(var21)
print()
print(var22)
print()
varadd2 = var21 + var22
print(varadd2)


[[1 2 3 4]
 [1 2 3 4]]

[[11 12 13 14]
 [11 12 13 14]]

[[12 14 16 18]
 [12 14 16 18]]


In [8]:
#operations on array in python

In [10]:
import numpy as np
var = np.array([1,2,3,4,9,5,3])
print(np.min(var))
print(np.max(var))

1
9


In [17]:
var1 = np.array([2,3,4,5,6,9,8,7])
print(np.min(var1),np.argmin(var1))
print(np.max(var1),np.argmax(var1))

2 0
9 5


In [34]:
val1 = ([1,2,3,4],[5,6,7,8])
print(np.max(val1,axis=1))

[4 8]


In [36]:
import numpy as np
var = np.array([3,2,1,4,5,3,2])
print("Minimum values:",np.min(var))
print("Maximum values:",np.max(var))
print("Square root :",np.sqrt(var))

Minimum values: 1
Maximum values: 5
Square root : [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]


In [37]:
var2 = np.array([1,2,3])
print(np.sin(var2))

[0.84147098 0.90929743 0.14112001]


In [38]:
var2 = np.array([3,4,6,7])
print(np.sin(var2))

[ 0.14112001 -0.7568025  -0.2794155   0.6569866 ]


In [49]:
var2 = np.array([[56,78,99],[45,90,30]])
print(np.cos(var2))

[[ 0.85322011 -0.85780309  0.03982088]
 [ 0.52532199 -0.44807362  0.15425145]]


In [53]:
var1 = np.array([[2,1,3],[9,6,7]])
print(np.min(var1))
print(np.max(var1))
print(np.cumsum(var1))

1
9
[ 2  3  6 15 21 28]


In [55]:
var2 = [(1,2,3,4,5,6,)]
print(np.cumsum(var2))

[ 1  3  6 10 15 21]


In [56]:
print(np.cumsum(var2))

[ 1  3  6 10 15 21]


In [57]:
var2 = [(1,2,4,5,6)]
print(np.cumsum(var2))

[ 1  3  7 12 18]


In [58]:
#Shape in Numpy

In [70]:
import numpy as np
var1 = np.array([[1,2,3,4],[4,5,6,7]])
print(np.cumsum(var1))

[ 1  3  6 10 14 19 25 32]


In [94]:
var1 = np.array([1,2,3,4,5], ndmin = 4)
print(var1)

print(var1.shape)

[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)


In [97]:
var2 = np.array([1,2,3,4,5,6],ndmin=4)
print(var2)
print(var2.ndim)
print()

[[[[1 2 3 4 5 6]]]]
4



In [106]:
var1 = np.array([1,2,3,4,5,6])
print(var1)
print(var1.reshape(3,2))
print(var1.ndim)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
1


In [109]:
var1 = np.array([1,2,3,4])
print(var1)
print(var1.reshape(2,2))
print(var1)

[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


In [149]:
var3= np.array([1,2,3,4,5,6,7,8,9,12,11,77])
print(var3)
print(var3.ndim)
print(var3.reshape(3,4))
print(var3.reshape(-1))

[ 1  2  3  4  5  6  7  8  9 12 11 77]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 12 11 77]]
[ 1  2  3  4  5  6  7  8  9 12 11 77]


In [165]:
import numpy as np
var1= np.array([2,3,4,5,6,7,8])
print(var1.shape)

var2 = np.array([[4],[5],[6],[7],[8],[9]])
print(var2)
print(var2.shape)

(7,)
[[4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(6, 1)


In [ ]:
x 