In [2]:
import numpy as np
var = np.array([9,8,7,6])


print(var[0])
print(var[1])
print(var[2])
print(var[3])

9
8
7
6


In [3]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)

[[9 8 7]
 [4 5 6]]
2


In [14]:
var2=np.array([[[1,2,3],[4,5,6]]])

print(var2)
print(var2.ndim)

print(var2[0,1,2])

[[[1 2 3]
  [4 5 6]]]
3
6


In [18]:
import numpy as np
var = np.array([9,8,7,6,5,4])

print(var)

print(var[0:4])
print(var[:])
print(var[:5])

[9 8 7 6 5 4]
[9 8 7 6]
[9 8 7 6 5 4]
[9 8 7 6 5]


In [22]:
import numpy as np

var = np.array([9,8,7,6,5])

print(var)

print(var[1:5])
var[0::2]

[9 8 7 6 5]
[8 7 6 5]


array([9, 7, 5])

In [24]:
var1 = np.array([[1,2,3,4,5],[5,6,7,8,9],[56,45,34,23,33]])

print(var1)
print()
print("6 to 9 :",var1[1,1:])

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [56 45 34 23 33]]

6 to 9 : [6 7 8 9]


In [26]:
import numpy as np

var = np.array([9,8,7,6,5])
print(var)
print()

for i in var:
    print(i)

[9 8 7 6 5]

9
8
7
6
5


In [28]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
    for k in j:
        print(k)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [33]:
var4=np.array([[[1,2,3,4],[5,6,7,8],[9,8,7,6]]])
print(var4)
print()
for i in var4:
    for j in i:
        for k in j:
            print(k)

print(var4)

[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 6]]]

1
2
3
4
5
6
7
8
9
8
7
6
[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 6]]]


In [36]:
var3 = np.array([[[9,8,7,6],[]]])

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [40]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4


In [58]:
var3 = np.array([[9,8,7,6],[1,2,3,4]])
print(var3)
print(var3.ndim)
for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[9 8 7 6]
 [1 2 3 4]]
2
b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'


In [60]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [65]:
import numpy as np
var = np.array([1,2,3,4])
co=var.copy()
var[1]=90
print("var : ",var)
print(co)

var :  [ 1 90  3  4]
[1 2 3 4]


In [66]:
import numpy as np
var = np.array([1,2,3,4])
co=var.view()
var[1]=90
print("var : ",var)
print(co)

var :  [ 1 90  3  4]
[ 1 90  3  4]
