In [14]:
import numpy as np
var = np.array([1,2,3,4])

np.random.shuffle(var)
print(var)

[3 4 1 2]


In [22]:
var1 = np.array([1,2,3,3,3,3,4,5])
np.unique(var1)


array([1, 2, 3, 4, 5])

In [33]:
var1=np.array([1,2,6,7,9,3,6])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 6, 7, 9]), array([0, 1, 5, 2, 3, 4], dtype=int64), array([1, 1, 1, 2, 1, 1], dtype=int64))


In [30]:
var2 = np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,4))
print(y)

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]


In [39]:
var2 = np.array([1,2,3,4,5,6])
y= np.resize(var2,(3,4))
print(y)

print(y.flatten())

[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6]


In [42]:
var2 = np.array([1,2,3,4])


[[1 2]
 [3 4]
 [5 6]]

Flatten : [1 3 5 2 4 6]
Ravel: [1 2 3 4 5 6]


In [45]:
import numpy as np

var = np.array([1,2,3,4])
print(var)
print(var.dtype)

[1 2 3 4]
int32


In [50]:
import numpy as np
var2=([1,2,3,4,5])
w=np.insert(var2,2,50)
print(var2)
print(w)

[1, 2, 3, 4, 5]
[ 1  2 50  3  4  5]


In [55]:
var1 = np.array([[1,2,3],[1,2,3]])
v1=np.insert(var1,1,44,axis=1)
print(v1)

[[ 1 44  2  3]
 [ 1 44  2  3]]


In [60]:
import numpy as np
v=np.array([1,2,3,4])
d=np.delete(v,2)
print()

[[1, 2, 3, 4], [6, 7, 8, 9]]
[[1 2 3 4]
 [6 7 8 9]]


[[1 2 3]
 [1 2 3]]
int32


numpy.ndarray

In [ ]:
impor